### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by kailash-prasad** [submission2019/cnn-quantization#6]
Quantize activation_pooling    | Id - None               | IntQuantizer - [bits: 8, clipping: no, bit_alloc_act: False, bit_alloc_weight: False, pcq_w: False, pcq_a: False, bcorr_act: False, bcorr_weight: False, vcorr_weight: False, kind: mean] | cuda:0
Segmentation fault (core dumped)

I am getting above mentioned error even if I try it with CPU? Can you help me with this?

**Comment by ynahshan** [comment]
Hi. This code requires cuda capable GPU to run. What is the GPU and cuda version you run on?

**Comment by submission2019** [comment]
closed

**Comment by ArsenLuca** [comment]
I also meet the problem. The cuda version I use is V9.0.176
The gpu is P40

**Comment by ArsenLuca** [comment]
@ynahshan as stated
